baseURL = ""
title = "OMEGA"
theme = "omega"
googleAnalytics = ""
themesDir = "themes"
publishDir = "public"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1

[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2

[[menu.main]]
name = "Products"
pre = "#"
url = "products"
weight = 3

[[menu.main]]
name = "Career"
pre = ""
url = "career"
weight = 4

[[menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 5

[params]
logo = "images/logo.png"
logo_width = "120px"
description = "This is meta description"
author = "Themefisher"
contact_info = "1001 Brickell bay <br>Dr. Miami, <br>FL 33131"
preloader = true

  [params.map]
  enable = true
  gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
  map_center_lat = "25.773606"
  map_center_lng = "-80.732655"
  map_position_lat = "25.7635916"
  map_position_lng = "-80.1937595"
  map_marker = "images/map-marker.png"

  [params.cookies]
  enable = true
  expire_days = 2

  [[params.social]]
  title = "facebook"
  icon = "fa-facebook"
  link = "#"

  [[params.social]]
  title = "twitter"
  icon = "fa-twitter"
  link = "#"

  [[params.social]]
  title = "instagram"
  icon = "fa-instagram"
  link = "#"

  [[params.social]]
  title = "github"
  icon = "fa-github"
  link = "#"

  [[params.social]]
  title = "linkedin"
  icon = "fa-linkedin"
  link = "#"
